### ISSUE TITLE
Configuration on Rasperrby Pi

### ISSUE THREAD

**Issue by mistyque** [Dean151/Aln-NodeJs#1]
hello, first of all thank you for this great job.
The honey guaridan S25 is fine, but its android application is really not ergonomic and buggy.

I wanted to use your API on my raspberry pi in order to control the feeder by my home automation Jeedom.

However, I lack elements to finish the configuration.

This is what I already did:
  - Wifi point on a raspberry pi
  - Connecting the manger to the created network
  - Install your API and add the conf to the /etc/rc.local file

I miss him :
  - In the "config.js" file, what should I put in "api_secret"?
  - should the API have been launched, if yes, how?

Thank you in advance !

**Comment by Dean151** [comment]
The config.js "api_secret" should contain a string that only you possess. It's a authetication key. Not ideal but enough to prevent anyone to use the API instead of you.
The same exact key is required to be given in the headers of the HTTP(S) requests you will then send to the API. It's just a security layer.

Then the API should be launch when needed ; using node.js : 
`# node /home/pi/Aln-NodeJs/main.js`
If you need the API to run forever, I recommand using the supervisor package ; that you're required to install and configure.
